[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev', 'npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan migrate --force && vendor/bin/heroku-php-apache2 public/'