services:
  - type: web
    name: noorelwegood
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        sync: false
